# Generated by Django 5.0.2 on 2024-02-27 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('parent', models.BooleanField(default=False)),
                ('guardian', models.BooleanField(default=False)),
                ('law_enforcer', models.BooleanField(default=False)),
                ('citizen', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'base_customuser',
            },
        ),
        migrations.CreateModel(
            name='Locationdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, null=True)),
                ('county', models.CharField(max_length=255, null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('division', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('sublocation', models.CharField(max_length=255, null=True)),
                ('town', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_tittle', models.CharField(max_length=255, null=True)),
                ('alert_type', models.CharField(choices=[('Missing_person', 'Missing person'), ('Missing_child', 'Missing child')], max_length=50, null=True)),
                ('alert_body', models.TextField(max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Found', 'Found')], max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.locationdata')),
            ],
        ),
        migrations.CreateModel(
            name='AlertRecipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.alerts')),
            ],
        ),
        migrations.CreateModel(
            name='ChildInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=50, null=True)),
                ('physical_description', models.TextField()),
                ('parent_contact', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.locationdata')),
            ],
        ),
        migrations.CreateModel(
            name='MissingPersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('physical_description', models.TextField(max_length=255, null=True)),
                ('family_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.locationdata')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('Missing child', 'Missing child'), ('Missing Person', 'Missing person')], max_length=50)),
                ('report_body', models.TextField(blank=True, null=True)),
                ('contact_information', models.CharField(blank=True, max_length=255, null=True)),
                ('police_report_number', models.CharField(max_length=255, null=True)),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.locationdata')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.childinformation')),
                ('missing_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.missingpersons')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('body', models.CharField(blank=True, max_length=255, null=True)),
                ('alerts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.alerts')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.reports')),
            ],
        ),
        migrations.AddField(
            model_name='alerts',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.reports'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('bio', models.TextField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('Citizen', 'Citizen'), ('Parent', 'parent'), ('Guardian', 'guardian'), ('Law_Enforcer', 'Law enforcer/police')], max_length=30, null=True)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
