# Generated by Django 5.0.2 on 2024-03-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customuser_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='module_perm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
