# Generated by Django 4.2.6 on 2023-11-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_users_email_alter_users_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('Citizen', 'Citizen'), ('Parent', 'parent'), ('Guardian', 'guardian'), ('Law_Enforcer', 'Law enforcer/police')], max_length=30, null=True),
        ),
    ]
