# Generated by Django 5.0.2 on 2024-03-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0003_customuser_module_perm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerts',
            old_name='alert_tittle',
            new_name='alert_title',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='admin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='citizen',
            new_name='is_citizen',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='guardian',
            new_name='is_guardian',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='law_enforcer',
            new_name='is_law_enforcer',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='parent',
            new_name='is_parent',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='staff',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='reports',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='email',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='module_perm',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='module_perms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='childinformation',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='missingpersons',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='AlertRecipients',
        ),
    ]
