# Generated by Django 4.2.6 on 2023-11-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_users_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childinformation',
            old_name='parent_name',
            new_name='parent_contact',
        ),
    ]
