# Generated by Django 5.0.2 on 2024-03-26 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_alert_tittle_alerts_alert_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missingperson_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='alerts',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='missingpersons',
            name='missingperson_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.images'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profle_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.images'),
        ),
    ]
