# Generated by Django 4.2.6 on 2023-11-07 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_locationdata_remove_childinformation_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childinformation',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.locationdata'),
        ),
        migrations.AddField(
            model_name='missingpersons',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.locationdata'),
        ),
        migrations.AddField(
            model_name='reports',
            name='Location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.locationdata'),
        ),
    ]
