# Generated by Django 4.2.6 on 2023-11-08 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_childinformation_location_missingpersons_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.locationdata'),
        ),
    ]
