# Generated by Django 5.0.2 on 2024-03-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_images_missingperson_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerts',
            options={'ordering': ('-created', '-updated')},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterModelOptions(
            name='reports',
            options={'ordering': ('-created', '-updated')},
        ),
    ]
