# Generated by Django 4.2.6 on 2023-11-13 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_reports_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.locationdata'),
        ),
    ]
