# Generated by Django 5.0.2 on 2024-04-05 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_alerts_options_alter_messages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdata',
            name='user_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.locationdata'),
        ),
    ]
