# Generated by Django 5.0.2 on 2024-04-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_locationdata_user_location_userprofile_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdata',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationdata',
            name='logitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
