# Generated by Django 4.2.6 on 2023-11-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alerts_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='alert_body',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
