# Generated by Django 5.0.2 on 2024-04-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
