# Generated by Django 5.0.2 on 2024-04-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_user_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
