# Generated by Django 5.0.2 on 2024-04-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_reports_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='users',
            new_name='user',
        ),
    ]
