# Generated by Django 5.0.2 on 2024-02-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='abc123@email.com', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
